# SPDX-FileCopyrightText: Copyright (c) 2024-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
# Based on https://github.com/yegor256/lecture-notes/blob/master/makefile.defs

SHELL := /bin/bash

.SHELLFLAGS = -e -o pipefail -c
.ONESHELL:
.PHONY: pdfs clean copy

DIRS = $(shell find . -mindepth 1 -maxdepth 2 -type d -name '[0-9][0-9]-*' | sed 's|^\./||'  | sort)
PDFS = $(foreach d,$(DIRS),$(d)/$(notdir $(d)).pdf)

debug:
	echo $(DIRS)

pdfs: $(PDFS)

%.pdf: %.tex
	dir="$$(dirname "$<")"
	echo $$dir
	cd "$${dir}"
	latexmk -pdf -xelatex

clean:
	work_dir="$$(pwd)"
	for d in $(DIRS); do
		cd $${d}
		latexmk -C
		cd $${work_dir}
	done
