# SPDX-FileCopyrightText: Copyright (c) 2023-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
name: latexmk
'on':
  push:
    branches:
      - master
jobs:
  latexmk:
    timeout-minutes: 15
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - run: sudo apt-get update --yes --fix-missing && sudo apt-get install --yes wget
      - uses: prafdin/latexmk-action@master # TODO: revert to yegor256 after resolve https://github.com/yegor256/latexmk-action/issues/102
        with:
          cmd: make
          depends: DEPENDS.txt
      - uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: package
          clean: true
        if: github.ref == 'refs/heads/master'