name: Deploy simple_site project to existing VM
on: 
  push: 
    branches:
      - 'rolling-update-test'
jobs:
  run-rolling-deploy-with-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install ansible
          python3 -m pip install yq
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Delete ssh key from hosts
        run: |
          yq -i -y 'del(.ungrouped.hosts.frontend.ansible_ssh_private_key_file)' ${{ github.workspace }}/simple_site/v1/ansible/hosts.yaml
      - name: Replace front ip fron variable
        run: |
           yq -y -i '.ungrouped.hosts.frontend.ansible_host = "${{ vars.PROD_FRONT_IP }}"' ${{ github.workspace }}/simple_site/v1/ansible/hosts.yaml
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ${{ github.workspace }}/simple_site/v1/ansible/upload_site.yaml
          directory: ${{ github.workspace }}/simple_site/v1/ansible/
          key: ${{secrets.YCLOUD_SSH_PRIVATE_KEY}}
          options: |
            --inventory ${{ github.workspace }}/simple_site/v1/ansible/hosts.yaml
