name: Deploy simple_site project to existing VM
on: 
  push: 
    branches:
      - 'github-actions-test'
jobs:
  run-deploy-with-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Install ansible
        run: |
          sudo apt-get update
          sudo apt-get install ansible 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: $GITHUB_WORKSPACE/simple_site/v1/ansible/upload_site.yaml
          # Optional, directory where playbooks live
          directory: $GITHUB_WORKSPACE/simple_site/v1/ansible/
          # Optional, SSH private key
          key: ${{secrets.YCLOUD_SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          options: |
            --inventory $GITHUB_WORKSPACE/simple_site/v1/ansible/hosts.yaml
